#!/usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use Wireshell\NewCommand;
use Wireshell\CreateUserCommand;
use Wireshell\CreateRoleCommand;
use Wireshell\CreateTemplateCommand;
use Wireshell\ServeCommand;
use Wireshell\OneclickCommand;
use GuzzleHttp\Client;

require 'vendor/autoload.php';

$app = new Application('WireShell - An extendable ProcessWire CLI', '0.1.0');

$app->add(new NewCommand(new Client));
$app->add(new CreateUserCommand());
$app->add(new CreateRoleCommand());
$app->add(new CreateTemplateCommand());
$app->add(new ServeCommand());
$app->add(new OneclickCommand());

$app->run();
