#!/usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use Wireshell\Commands\NewCommand;
use Wireshell\Commands\CreateUserCommand;
use Wireshell\Commands\CreateRoleCommand;
use Wireshell\Commands\CreateTemplateCommand;
use Wireshell\Commands\CreateFieldCommand;
use Wireshell\Commands\ServeCommand;
use Wireshell\Commands\ShowVersionCommand;
use Wireshell\Commands\TemplateFieldsCommand;
use Wireshell\Commands\BackupCommand;
use Wireshell\Commands\ModuleEnableCommand;
use Wireshell\Commands\ModuleDisableCommand;
require 'vendor/autoload.php';

$app = new Application('WireShell - An extendable ProcessWire CLI', '0.3.0');

$app->add(new NewCommand());
$app->add(new CreateUserCommand());
$app->add(new CreateRoleCommand());
$app->add(new CreateTemplateCommand());
$app->add(new ServeCommand());
$app->add(new ShowVersionCommand());
$app->add(new TemplateFieldsCommand());
$app->add(new CreateFieldCommand());
$app->add(new BackupCommand());
$app->add(new ModuleEnableCommand());
$app->add(new ModuleDisableCommand());

$app->run();
